# Generated by Django 2.0.13 on 2020-08-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchnews',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
