# Generated by Django 2.0.13 on 2020-08-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20200820_0336'),
        ('community', '0007_auto_20200820_1550'),
    ]

    operations = [
    ]
